using MPAi.Components;
using MPAi.Modules;
using System;
using System.Windows.Forms;

namespace MPAi.Forms.Popups
{
    public partial class UserCreationScreen : Form
    {
        private string username = null;
        private string usercode = null;
        private VoiceType voiceType = null;

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public UserCreationScreen()
        {
            InitializeComponent();

            AcceptButton = this.okayButton;
        }

        /// <summary>
        /// Gets the values of the user from the text boxes, and uses them to create an MPAi user object.
        /// </summary>
        /// <returns>The created user object.</returns>
        public MPAiUser getCandidate()
        {
            username = userNameBox.Text;
            usercode = passwordBox.Text;
            if(masculineRadioButton.Checked && nativeRadioButton.Checked)
            {
                voiceType = new VoiceType(GenderType.MASCULINE, LanguageType.NATIVE);
            }
            else if (masculineRadioButton.Checked && modernRadioButton.Checked)
            {
                voiceType = new VoiceType(GenderType.MASCULINE, LanguageType.MODERN);
            }
            else if (feminineRadioButton.Checked && nativeRadioButton.Checked)
            {
                voiceType = new VoiceType(GenderType.FEMININE, LanguageType.NATIVE);
            }
            else if (feminineRadioButton.Checked && modernRadioButton.Checked)
            {
                voiceType = new VoiceType(GenderType.FEMININE, LanguageType.MODERN);
            }

            return (new MPAiUser(username, usercode, voiceType));
        }

        private void UserCreationScreen_Load(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Ensures that the new user is valid, and closes the window.
        /// </summary>
        private void createUser()
        {
            if (userNameBox.Text.Trim() == "")
            {
                MPAiMessageBoxFactory.Show("Username should not be empty! ",
                  "Oops", MPAiMessageBoxButtons.OK);
                return;
            }
            else if ((passwordBox.Text.Trim() == "") || (confirmPasswordBox.Text.Trim() == ""))
            {
                MPAiMessageBoxFactory.Show("Passwords should not be empty! ",
                   "Oops", MPAiMessageBoxButtons.OK);
                return;
            }
            else if (passwordBox.Text != confirmPasswordBox.Text)
            {
                MPAiMessageBoxFactory.Show("Passwords do not match! ",
                    "Oops", MPAiMessageBoxButtons.OK);
                return;
            }

            MPAiUser candidate = getCandidate();

            if (!UserManagement.CreateNewUser(candidate))
            {
                MPAiMessageBoxFactory.Show("User already exists, please use a different name! ",
                    "Oops", MPAiMessageBoxButtons.OK);
            }
            else
            {
                MPAiMessageBoxFactory.Show("Registration successful! ",
                        "Congratulations", MPAiMessageBoxButtons.OK);
                UserManagement.WriteSettings();
                LoginScreen loginWindow = (LoginScreen)Owner;      // Only LoginWindow can open this form.
                loginWindow.VisualizeUser(candidate);
                Close();
            }
        }

        /// <summary>
        /// Closes the window if the operation is cancelled.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void cancelButton_Click(object sender, EventArgs e)
        {
            Close();
        }

        /// <summary>
        /// When the ok button is pressed, calls the method to verify the new user.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void okayButton_Click(object sender, EventArgs e)
        {
            createUser();
        }

        private void masculineRadioButton_CheckedChanged(object sender, EventArgs e)
        {
            if(masculineRadioButton.Checked)
            {
                nativeRadioButton.Text = DisplayVoice.DisplayNative(GenderType.MASCULINE);
            }
            else
            {
                nativeRadioButton.Text = DisplayVoice.DisplayNative(GenderType.FEMININE);
            }
        }

        private void feminineRadioButton_CheckedChanged(object sender, EventArgs e)
        {
            if (feminineRadioButton.Checked)
            {
                nativeRadioButton.Text = DisplayVoice.DisplayNative(GenderType.FEMININE);
            }
            else
            {
                nativeRadioButton.Text = DisplayVoice.DisplayNative(GenderType.MASCULINE);
            }
        }
    }
}
